apiVersion: v1
kind: Service
metadata:
  name: flask-test
spec:
  selector:
    app: flask-test
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-test
spec:
  selector:
    matchLabels:
      app: flask-test
  replicas: 3
  template:
    metadata:
      labels:
        app: flask-test
    spec:
      containers:
        - name: flask-test
          image: docker.io/moskst/minikube-flask-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

