apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/instance: flask
    app.kubernetes.io/name: flask
  name: flask

---
apiVersion: v1
kind: Service
metadata:
  name: flask
  namespace: flask
spec:
  type: LoadBalancer
  selector:
    app: flask
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  namespace: flask
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 3
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: docker.io/moskst/minikube-flask-app:latest
          ports:
            - containerPort: 80
#--- 
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: flask
#  namespace: flask
#spec:
#  ingressClassName: nginx
#  rules:
#  - host: flask.localdomain.me
#    http:
#      paths:
#      - backend:
#          service:
#            name: flask
#            port:
#              number: 80
#        path: /flask
#        pathType: Prefix
